#INCLUDE "P16F877A.INC"  ;

__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_OFF & _BODEN_OFF & _LVP_OFF & _HS_OSC ; 
	
	
RES_VECT  CODE    0x00      ; processor reset vector
	  GOTO    CONFI     ; go to beginning of program
  
INT_VECT  CODE 0X04	    ; interrupt vector
	  GOTO    ISR	    ; go to interrupt service routine 	

 
CONFI	BSF STATUS,RP0
	MOVLW H'00'
	MOVWF TRISD	;PORT D OUTPUT
	MOVLW H'FF'
	MOVWF TRISC	;PORT C UART MODE
	MOVLW D'25'
	MOVWF SPBRG	; SET SPBRG TO 9600 
	MOVLW H'04'	
	MOVWF TXSTA
	MOVLW H'C0'	    ;GIE ENABLED ;PEIE ENABLED
	MOVWF INTCON
	MOVLW H'20'	    ;RCIE ENABLED
	MOVWF PIE1
	BCF STATUS,RP0
	MOVLW H'90'	
	MOVWF RCSTA
	GOTO MAIN
	
ISR	MOVF RCREG,W 	 ; RECIEVE DATA
	MOVWF PORTD	 ; OUTPUT TO PORT D
	BCF PIE1,RCIF
	RETFIE
	
MAIN	GOTO MAIN
	
END
